### ISSUE TITLE
Indicator is still showing when withIndicator is not passed as a prop

### ISSUE THREAD

**Issue by rahmanharoon** [katanyaJATI/react-native-image-blur-loading#10]
*I don't want to show activity indicator so I removed withIndicator props* and still its showing Activity indicator in the bottom. In documentation its given as not required

Here is the code I tried first  
```
   <ImageBlurLoading
        thumbnailSource={{uri: sliderImage}}
        source={{uri: sliderImage}}
        style={[sliderStyle.imageHeight]}
     />
 ```

Here is the result of the above result
![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-08-10 at 13 08 51](https://user-images.githubusercontent.com/67966429/128830506-b8878c4f-eeaf-4446-aa33-7e3c8c2f7b0f.png)

After that I passed withIndicator={false} and its working fine

```
<ImageBlurLoading
          withIndicator={false}
          thumbnailSource={{uri: sliderImage}}
          source={{uri: sliderImage}}
          style={[sliderStyle.imageHeight]}
/>
```

**Comment by hxffy** [comment]
This happens because the default value of withIndicator is `true`

https://github.com/katanyaJATI/react-native-image-blur-loading/blob/94eba344ca1f84702e11980850256aed859d9060/src/index.tsx#L27
