### ISSUE TITLE
Animated: `useNativeDriver` was not specified warning

### ISSUE THREAD

**Issue by pdugan20** [katanyaJATI/react-native-image-blur-loading#2]
Getting a useNativeDriver warning on RN 0.62.
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

**Comment by katanyaJATI** [comment]
Hi @pdugan20, thanks for the feedback! The issue has been resolved in version 1.1.0.
Enjoy! :wink:
