### ISSUE TITLE
undefined is not an object (evaluating style.borderBottomLeftRadius)

### ISSUE THREAD

**Issue by FrederickEngelhardt** [katanyaJATI/react-native-image-blur-loading#6]
When not providing a style for the ResizeImage I get the following error.

undefined is not an object (evaluating style.borderBottomLeftRadius)

Perhaps the default styles need to be fixed?

**Comment by katanyaJATI** [comment]
Hi @FrederickEngelhardt, thanks for the feedback! The issue has been resolved in version 1.1.5.
Enjoy! 😉
